// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uxyvzfsvomsaxlnnhbvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4eXZ6ZnN2b21zYXhsbm5oYnZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODc1NjEsImV4cCI6MjA3MDM2MzU2MX0.TRXVm86a47Iy-mG_1iVF_AF8LOlWQzx1XTWd-GMr6qo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);